### ISSUE TITLE
Document Format

### ISSUE THREAD

**Issue by micknudsen** [NEXTBioinformatics/Best-Practices-for-Processing-HTS-Data#1]
Since the document will contain lots and lots of code and command line arguments, maybe we should consider a different format than LaTeX?

How about something like _Read the Docs_ (RTD)? If you are not familiar with RTD, have a look at the [CNVkit repository](https://github.com/etal/cnvkit) (we use this tool at MOMA). The [documentation](http://cnvkit.readthedocs.io/en/stable/) is written in RTD.

To me, it seems that RTD (or something similar) is the ideal framework for structuring a _Best Practices_ document.

**Comment by rfbrondum** [comment]
I am open for switching the format, and the layout of RTD seems quite good, so if it is an easy switch I have no problem.

**Comment by mboegsted** [comment]
Seems like a good idea, please go ahead!

**Comment by micknudsen** [comment]
I have now completed the transition to Read the Docs (but not added content back yet). Does it work for all of you? Clicking the 'docs' badge in the README file hopefully takes you to a beautifully rendered version of the docs. It will be updated automatically each time a new version is pushed to GitHub.

It is possible to build the pages locally by simply running 'make html', but you may have to install some Python dependencies first.

**Comment by rfbrondum** [comment]
Great work, the docs button works just fine here!
